import { Pool } from "pg";
import { connectPostgres } from "../src";

// const models = [
//   { name: "A3", brand: "Audi" },
//   { name: "A4", brand: "Audi" },
//   { name: "A6", brand: "Audi" },
//   { name: "Q5", brand: "Audi" },
//   { name: "3 Series", brand: "BMW" },
//   { name: "5 Series", brand: "BMW" },
//   { name: "X3", brand: "BMW" },
//   { name: "X5", brand: "BMW" },
//   { name: "Silverado", brand: "Chevrolet" },
//   { name: "Malibu", brand: "Chevrolet" },
//   { name: "Equinox", brand: "Chevrolet" },
//   { name: "Cruze", brand: "Chevrolet" },
//   { name: "Charger", brand: "Dodge" },
//   { name: "Challenger", brand: "Dodge" },
//   { name: "Durango", brand: "Dodge" },
//   { name: "Journey", brand: "Dodge" },
//   { name: "F-150", brand: "Ford" },
//   { name: "Mustang", brand: "Ford" },
//   { name: "Explorer", brand: "Ford" },
//   { name: "Escape", brand: "Ford" },
//   { name: "Sierra", brand: "GMC" },
//   { name: "Terrain", brand: "GMC" },
//   { name: "Yukon", brand: "GMC" },
//   { name: "Acadia", brand: "GMC" },
//   { name: "Civic", brand: "Honda" },
//   { name: "Accord", brand: "Honda" },
//   { name: "CR-V", brand: "Honda" },
//   { name: "Pilot", brand: "Honda" },
//   { name: "Elantra", brand: "Hyundai" },
//   { name: "Sonata", brand: "Hyundai" },
//   { name: "Tucson", brand: "Hyundai" },
//   { name: "Santa Fe", brand: "Hyundai" },
//   { name: "Q50", brand: "Infiniti" },
//   { name: "Q60", brand: "Infiniti" },
//   { name: "QX50", brand: "Infiniti" },
//   { name: "QX80", brand: "Infiniti" },
//   { name: "Cherokee", brand: "Jeep" },
//   { name: "Grand Cherokee", brand: "Jeep" },
//   { name: "Wrangler", brand: "Jeep" },
//   { name: "Compass", brand: "Jeep" },
//   { name: "Optima", brand: "Kia" },
//   { name: "Forte", brand: "Kia" },
//   { name: "Sorento", brand: "Kia" },
//   { name: "Sportage", brand: "Kia" },
//   { name: "ES", brand: "Lexus" },
//   { name: "RX", brand: "Lexus" },
//   { name: "NX", brand: "Lexus" },
//   { name: "IS", brand: "Lexus" },
//   { name: "3", brand: "Mazda" },
//   { name: "6", brand: "Mazda" },
//   { name: "CX-5", brand: "Mazda" },
//   { name: "CX-9", brand: "Mazda" },
//   { name: "C-Class", brand: "Mercedes-Benz" },
//   { name: "E-Class", brand: "Mercedes-Benz" },
//   { name: "GLC", brand: "Mercedes-Benz" },
//   { name: "GLE", brand: "Mercedes-Benz" },
//   { name: "Outlander", brand: "Mitsubishi" },
//   { name: "Eclipse Cross", brand: "Mitsubishi" },
//   { name: "Mirage", brand: "Mitsubishi" },
//   { name: "Pajero", brand: "Mitsubishi" },
//   { name: "Altima", brand: "Nissan" },
//   { name: "Maxima", brand: "Nissan" },
//   { name: "Rogue", brand: "Nissan" },
//   { name: "Sentra", brand: "Nissan" },
//   { name: "911", brand: "Porsche" },
//   { name: "Cayenne", brand: "Porsche" },
//   { name: "Macan", brand: "Porsche" },
//   { name: "Panamera", brand: "Porsche" },
//   { name: "1500", brand: "Ram" },
//   { name: "2500", brand: "Ram" },
//   { name: "3500", brand: "Ram" },
//   { name: "ProMaster", brand: "Ram" },
//   { name: "Model 3", brand: "Tesla" },
//   { name: "Model S", brand: "Tesla" },
//   { name: "Model X", brand: "Tesla" },
//   { name: "Model Y", brand: "Tesla" },
//   { name: "Camry", brand: "Toyota" },
//   { name: "Corolla", brand: "Toyota" },
//   { name: "RAV4", brand: "Toyota" },
//   { name: "Highlander", brand: "Toyota" },
//   { name: "Golf", brand: "Volkswagen" },
//   { name: "Jetta", brand: "Volkswagen" },
//   { name: "Passat", brand: "Volkswagen" },
//   { name: "Tiguan", brand: "Volkswagen" },
//   { name: "ILX", brand: "Acura" },
//   { name: "MDX", brand: "Acura" },
//   { name: "RDX", brand: "Acura" },
//   { name: "TLX", brand: "Acura" },
//   { name: "Giulia", brand: "Alfa Romeo" },
//   { name: "Stelvio", brand: "Alfa Romeo" },
//   { name: "4C", brand: "Alfa Romeo" },
//   { name: "Tonale", brand: "Alfa Romeo" },
//   { name: "DB11", brand: "Aston Martin" },
//   { name: "DBS", brand: "Aston Martin" },
//   { name: "Vantage", brand: "Aston Martin" },
//   { name: "DBX", brand: "Aston Martin" },
//   { name: "Continental GT", brand: "Bentley" },
//   { name: "Flying Spur", brand: "Bentley" },
//   { name: "Bentayga", brand: "Bentley" },
//   { name: "Mulsanne", brand: "Bentley" },
//   { name: "Enclave", brand: "Buick" },
//   { name: "Encore", brand: "Buick" },
//   { name: "Envision", brand: "Buick" },
//   { name: "LaCrosse", brand: "Buick" },
//   { name: "CT4", brand: "Cadillac" },
//   { name: "CT5", brand: "Cadillac" },
//   { name: "Escalade", brand: "Cadillac" },
//   { name: "XT5", brand: "Cadillac" },
//   { name: "300", brand: "Chrysler" },
//   { name: "Pacifica", brand: "Chrysler" },
//   { name: "Voyager", brand: "Chrysler" },
//   { name: "C3", brand: "Citroen" },
//   { name: "C4", brand: "Citroen" },
//   { name: "C5", brand: "Citroen" },
//   { name: "Berlingo", brand: "Citroen" },
//   { name: "Sandero", brand: "Dacia" },
//   { name: "Duster", brand: "Dacia" },
//   { name: "Logan", brand: "Dacia" },
//   { name: "Spring", brand: "Dacia" },
//   { name: "F8 Tributo", brand: "Ferrari" },
//   { name: "SF90 Stradale", brand: "Ferrari" },
//   { name: "Roma", brand: "Ferrari" },
//   { name: "Portofino", brand: "Ferrari" },
//   { name: "500", brand: "Fiat" },
//   { name: "Panda", brand: "Fiat" },
//   { name: "Tipo", brand: "Fiat" },
//   { name: "500X", brand: "Fiat" },
//   { name: "Aventador", brand: "Lamborghini" },
//   { name: "Huracan", brand: "Lamborghini" },
//   { name: "Urus", brand: "Lamborghini" },
//   { name: "Sian", brand: "Lamborghini" },
//   { name: "Evora", brand: "Lotus" },
//   { name: "Elise", brand: "Lotus" },
//   { name: "Emira", brand: "Lotus" },
//   { name: "Evija", brand: "Lotus" },
//   { name: "Ghibli", brand: "Maserati" },
//   { name: "Levante", brand: "Maserati" },
//   { name: "Quattroporte", brand: "Maserati" },
//   { name: "MC20", brand: "Maserati" },
//   { name: "720S", brand: "McLaren" },
//   { name: "GT", brand: "McLaren" },
//   { name: "Artura", brand: "McLaren" },
//   { name: "765LT", brand: "McLaren" },
//   { name: "Astra", brand: "Opel" },
//   { name: "Corsa", brand: "Opel" },
//   { name: "Mokka", brand: "Opel" },
//   { name: "Insignia", brand: "Opel" },
//   { name: "208", brand: "Peugeot" },
//   { name: "308", brand: "Peugeot" },
//   { name: "3008", brand: "Peugeot" },
//   { name: "5008", brand: "Peugeot" },
//   { name: "Clio", brand: "Renault" },
//   { name: "Megane", brand: "Renault" },
//   { name: "Captur", brand: "Renault" },
//   { name: "Zoe", brand: "Renault" },
//   { name: "Leon", brand: "Seat" },
//   { name: "Ibiza", brand: "Seat" },
//   { name: "Ateca", brand: "Seat" },
//   { name: "Arona", brand: "Seat" },
//   { name: "Octavia", brand: "Skoda" },
//   { name: "Superb", brand: "Skoda" },
//   { name: "Kodiaq", brand: "Skoda" },
//   { name: "Karoq", brand: "Skoda" },
//   { name: "Impreza", brand: "Subaru" },
//   { name: "Outback", brand: "Subaru" },
//   { name: "Forester", brand: "Subaru" },
//   { name: "WRX", brand: "Subaru" },
//   { name: "Swift", brand: "Suzuki" },
//   { name: "Vitara", brand: "Suzuki" },
//   { name: "Jimny", brand: "Suzuki" },
//   { name: "S-Cross", brand: "Suzuki" },
//   { name: "Harrier", brand: "Tata" },
//   { name: "Nexon", brand: "Tata" },
//   { name: "Safari", brand: "Tata" },
//   { name: "Altroz", brand: "Tata" },
// ];
const spares = [
  // Audi A3
  {
    name: "Brake Pads",
    sku: "A3-BRK-001",
    code: "BP",
    price: 89.99,
    model: "A3",
  },
  {
    name: "Oil Filter",
    sku: "A3-ENG-001",
    code: "OF",
    price: 15.99,
    model: "A3",
  },
  {
    name: "Air Filter",
    sku: "A3-ENG-002",
    code: "AF",
    price: 24.99,
    model: "A3",
  },
  {
    name: "Spark Plugs",
    sku: "A3-ENG-003",
    code: "SP",
    price: 12.99,
    model: "A3",
  },
  {
    name: "Wiper Blades",
    sku: "A3-EXT-001",
    code: "WB",
    price: 29.99,
    model: "A3",
  },
  {
    name: "Headlight Bulb",
    sku: "A3-ELE-001",
    code: "HB",
    price: 19.99,
    model: "A3",
  },
  {
    name: "Battery",
    sku: "A3-ELE-002",
    code: "BAT",
    price: 149.99,
    model: "A3",
  },
  {
    name: "Alternator",
    sku: "A3-ELE-003",
    code: "ALT",
    price: 299.99,
    model: "A3",
  },
  {
    name: "Timing Belt",
    sku: "A3-ENG-004",
    code: "TB",
    price: 49.99,
    model: "A3",
  },
  {
    name: "Water Pump",
    sku: "A3-ENG-005",
    code: "WP",
    price: 89.99,
    model: "A3",
  },

  // BMW 3 Series
  {
    name: "Brake Pads",
    sku: "3S-BRK-001",
    code: "BP",
    price: 99.99,
    model: "3 Series",
  },
  {
    name: "Oil Filter",
    sku: "3S-ENG-001",
    code: "OF",
    price: 18.99,
    model: "3 Series",
  },
  {
    name: "Air Filter",
    sku: "3S-ENG-002",
    code: "AF",
    price: 27.99,
    model: "3 Series",
  },
  {
    name: "Spark Plugs",
    sku: "3S-ENG-003",
    code: "SP",
    price: 14.99,
    model: "3 Series",
  },
  {
    name: "Wiper Blades",
    sku: "3S-EXT-001",
    code: "WB",
    price: 32.99,
    model: "3 Series",
  },
  {
    name: "Headlight Bulb",
    sku: "3S-ELE-001",
    code: "HB",
    price: 22.99,
    model: "3 Series",
  },
  {
    name: "Battery",
    sku: "3S-ELE-002",
    code: "BAT",
    price: 159.99,
    model: "3 Series",
  },
  {
    name: "Alternator",
    sku: "3S-ELE-003",
    code: "ALT",
    price: 319.99,
    model: "3 Series",
  },
  {
    name: "Timing Belt",
    sku: "3S-ENG-004",
    code: "TB",
    price: 54.99,
    model: "3 Series",
  },
  {
    name: "Water Pump",
    sku: "3S-ENG-005",
    code: "WP",
    price: 94.99,
    model: "3 Series",
  },

  // Toyota Camry
  {
    name: "Brake Pads",
    sku: "CAM-BRK-001",
    code: "BP",
    price: 79.99,
    model: "Camry",
  },
  {
    name: "Oil Filter",
    sku: "CAM-ENG-001",
    code: "OF",
    price: 13.99,
    model: "Camry",
  },
  {
    name: "Air Filter",
    sku: "CAM-ENG-002",
    code: "AF",
    price: 21.99,
    model: "Camry",
  },
  {
    name: "Spark Plugs",
    sku: "CAM-ENG-003",
    code: "SP",
    price: 9.99,
    model: "Camry",
  },
  {
    name: "Wiper Blades",
    sku: "CAM-EXT-001",
    code: "WB",
    price: 24.99,
    model: "Camry",
  },
  {
    name: "Headlight Bulb",
    sku: "CAM-ELE-001",
    code: "HB",
    price: 17.99,
    model: "Camry",
  },
  {
    name: "Battery",
    sku: "CAM-ELE-002",
    code: "BAT",
    price: 129.99,
    model: "Camry",
  },
  {
    name: "Alternator",
    sku: "CAM-ELE-003",
    code: "ALT",
    price: 279.99,
    model: "Camry",
  },
  {
    name: "Timing Belt",
    sku: "CAM-ENG-004",
    code: "TB",
    price: 44.99,
    model: "Camry",
  },
  {
    name: "Water Pump",
    sku: "CAM-ENG-005",
    code: "WP",
    price: 79.99,
    model: "Camry",
  },

  // Honda Civic
  {
    name: "Brake Pads",
    sku: "CIV-BRK-001",
    code: "BP",
    price: 74.99,
    model: "Civic",
  },
  {
    name: "Oil Filter",
    sku: "CIV-ENG-001",
    code: "OF",
    price: 12.99,
    model: "Civic",
  },
  {
    name: "Air Filter",
    sku: "CIV-ENG-002",
    code: "AF",
    price: 19.99,
    model: "Civic",
  },
  {
    name: "Spark Plugs",
    sku: "CIV-ENG-003",
    code: "SP",
    price: 8.99,
    model: "Civic",
  },
  {
    name: "Wiper Blades",
    sku: "CIV-EXT-001",
    code: "WB",
    price: 22.99,
    model: "Civic",
  },
  {
    name: "Headlight Bulb",
    sku: "CIV-ELE-001",
    code: "HB",
    price: 16.99,
    model: "Civic",
  },
  {
    name: "Battery",
    sku: "CIV-ELE-002",
    code: "BAT",
    price: 119.99,
    model: "Civic",
  },
  {
    name: "Alternator",
    sku: "CIV-ELE-003",
    code: "ALT",
    price: 269.99,
    model: "Civic",
  },
  {
    name: "Timing Belt",
    sku: "CIV-ENG-004",
    code: "TB",
    price: 42.99,
    model: "Civic",
  },
  {
    name: "Water Pump",
    sku: "CIV-ENG-005",
    code: "WP",
    price: 76.99,
    model: "Civic",
  },

  // Ford Mustang
  {
    name: "Brake Pads",
    sku: "MUS-BRK-001",
    code: "BP",
    price: 94.99,
    model: "Mustang",
  },
  {
    name: "Oil Filter",
    sku: "MUS-ENG-001",
    code: "OF",
    price: 16.99,
    model: "Mustang",
  },
  {
    name: "Air Filter",
    sku: "MUS-ENG-002",
    code: "AF",
    price: 25.99,
    model: "Mustang",
  },
  {
    name: "Spark Plugs",
    sku: "MUS-ENG-003",
    code: "SP",
    price: 11.99,
    model: "Mustang",
  },
  {
    name: "Wiper Blades",
    sku: "MUS-EXT-001",
    code: "WB",
    price: 28.99,
    model: "Mustang",
  },
  {
    name: "Headlight Bulb",
    sku: "MUS-ELE-001",
    code: "HB",
    price: 20.99,
    model: "Mustang",
  },
  {
    name: "Battery",
    sku: "MUS-ELE-002",
    code: "BAT",
    price: 139.99,
    model: "Mustang",
  },
  {
    name: "Alternator",
    sku: "MUS-ELE-003",
    code: "ALT",
    price: 289.99,
    model: "Mustang",
  },
  {
    name: "Timing Belt",
    sku: "MUS-ENG-004",
    code: "TB",
    price: 47.99,
    model: "Mustang",
  },
  {
    name: "Water Pump",
    sku: "MUS-ENG-005",
    code: "WP",
    price: 84.99,
    model: "Mustang",
  },

  // Mercedes C-Class
  {
    name: "Brake Pads",
    sku: "CC-BRK-001",
    code: "BP",
    price: 109.99,
    model: "C-Class",
  },
  {
    name: "Oil Filter",
    sku: "CC-ENG-001",
    code: "OF",
    price: 19.99,
    model: "C-Class",
  },
  {
    name: "Air Filter",
    sku: "CC-ENG-002",
    code: "AF",
    price: 29.99,
    model: "C-Class",
  },
  {
    name: "Spark Plugs",
    sku: "CC-ENG-003",
    code: "SP",
    price: 15.99,
    model: "C-Class",
  },
  {
    name: "Wiper Blades",
    sku: "CC-EXT-001",
    code: "WB",
    price: 34.99,
    model: "C-Class",
  },
  {
    name: "Headlight Bulb",
    sku: "CC-ELE-001",
    code: "HB",
    price: 24.99,
    model: "C-Class",
  },
  {
    name: "Battery",
    sku: "CC-ELE-002",
    code: "BAT",
    price: 169.99,
    model: "C-Class",
  },
  {
    name: "Alternator",
    sku: "CC-ELE-003",
    code: "ALT",
    price: 329.99,
    model: "C-Class",
  },
  {
    name: "Timing Belt",
    sku: "CC-ENG-004",
    code: "TB",
    price: 59.99,
    model: "C-Class",
  },
  {
    name: "Water Pump",
    sku: "CC-ENG-005",
    code: "WP",
    price: 99.99,
    model: "C-Class",
  },

  // Porsche 911
  {
    name: "Brake Pads",
    sku: "911-BRK-001",
    code: "BP",
    price: 199.99,
    model: "911",
  },
  {
    name: "Oil Filter",
    sku: "911-ENG-001",
    code: "OF",
    price: 29.99,
    model: "911",
  },
  {
    name: "Air Filter",
    sku: "911-ENG-002",
    code: "AF",
    price: 39.99,
    model: "911",
  },
  {
    name: "Spark Plugs",
    sku: "911-ENG-003",
    code: "SP",
    price: 24.99,
    model: "911",
  },
  {
    name: "Wiper Blades",
    sku: "911-EXT-001",
    code: "WB",
    price: 44.99,
    model: "911",
  },
  {
    name: "Headlight Bulb",
    sku: "911-ELE-001",
    code: "HB",
    price: 34.99,
    model: "911",
  },
  {
    name: "Battery",
    sku: "911-ELE-002",
    code: "BAT",
    price: 249.99,
    model: "911",
  },
  {
    name: "Alternator",
    sku: "911-ELE-003",
    code: "ALT",
    price: 449.99,
    model: "911",
  },
  {
    name: "Timing Belt",
    sku: "911-ENG-004",
    code: "TB",
    price: 89.99,
    model: "911",
  },
  {
    name: "Water Pump",
    sku: "911-ENG-005",
    code: "WP",
    price: 149.99,
    model: "911",
  },

  // Ferrari 488
  {
    name: "Brake Pads",
    sku: "488-BRK-001",
    code: "BP",
    price: 299.99,
    model: "488",
  },
  {
    name: "Oil Filter",
    sku: "488-ENG-001",
    code: "OF",
    price: 49.99,
    model: "488",
  },
  {
    name: "Air Filter",
    sku: "488-ENG-002",
    code: "AF",
    price: 79.99,
    model: "488",
  },
  {
    name: "Spark Plugs",
    sku: "488-ENG-003",
    code: "SP",
    price: 39.99,
    model: "488",
  },
  {
    name: "Wiper Blades",
    sku: "488-EXT-001",
    code: "WB",
    price: 59.99,
    model: "488",
  },
  {
    name: "Headlight Bulb",
    sku: "488-ELE-001",
    code: "HB",
    price: 49.99,
    model: "488",
  },
  {
    name: "Battery",
    sku: "488-ELE-002",
    code: "BAT",
    price: 299.99,
    model: "488",
  },
  {
    name: "Alternator",
    sku: "488-ELE-003",
    code: "ALT",
    price: 599.99,
    model: "488",
  },
  {
    name: "Timing Belt",
    sku: "488-ENG-004",
    code: "TB",
    price: 149.99,
    model: "488",
  },
  {
    name: "Water Pump",
    sku: "488-ENG-005",
    code: "WP",
    price: 249.99,
    model: "488",
  },

  // Aston Martin DB11
  {
    name: "Brake Pads",
    sku: "DB11-BRK-001",
    code: "BP",
    price: 399.99,
    model: "DB11",
  },
  {
    name: "Oil Filter",
    sku: "DB11-ENG-001",
    code: "OF",
    price: 69.99,
    model: "DB11",
  },
  {
    name: "Air Filter",
    sku: "DB11-ENG-002",
    code: "AF",
    price: 109.99,
    model: "DB11",
  },
  {
    name: "Spark Plugs",
    sku: "DB11-ENG-003",
    code: "SP",
    price: 59.99,
    model: "DB11",
  },
  {
    name: "Wiper Blades",
    sku: "DB11-EXT-001",
    code: "WB",
    price: 79.99,
    model: "DB11",
  },
  {
    name: "Headlight Bulb",
    sku: "DB11-ELE-001",
    code: "HB",
    price: 69.99,
    model: "DB11",
  },
  {
    name: "Battery",
    sku: "DB11-ELE-002",
    code: "BAT",
    price: 399.99,
    model: "DB11",
  },
  {
    name: "Alternator",
    sku: "DB11-ELE-003",
    code: "ALT",
    price: 799.99,
    model: "DB11",
  },
  {
    name: "Timing Belt",
    sku: "DB11-ENG-004",
    code: "TB",
    price: 249.99,
    model: "DB11",
  },
  {
    name: "Water Pump",
    sku: "DB11-ENG-005",
    code: "WP",
    price: 149.99,
    model: "DB11",
  },

  // Bentley Continental GT
  {
    name: "Brake Pads",
    sku: "CONT-BRK-001",
    code: "BP",
    price: 499.99,
    model: "Continental GT",
  },
  {
    name: "Oil Filter",
    sku: "CONT-ENG-001",
    code: "OF",
    price: 89.99,
    model: "Continental GT",
  },
  {
    name: "Air Filter",
    sku: "CONT-ENG-002",
    code: "AF",
    price: 139.99,
    model: "Continental GT",
  },
  {
    name: "Spark Plugs",
    sku: "CONT-ENG-003",
    code: "SP",
    price: 79.99,
    model: "Continental GT",
  },
  {
    name: "Wiper Blades",
    sku: "CONT-EXT-001",
    code: "WB",
    price: 99.99,
    model: "Continental GT",
  },
  {
    name: "Headlight Bulb",
    sku: "CONT-ELE-001",
    code: "HB",
    price: 89.99,
    model: "Continental GT",
  },
  {
    name: "Battery",
    sku: "CONT-ELE-002",
    code: "BAT",
    price: 499.99,
    model: "Continental GT",
  },
  {
    name: "Alternator",
    sku: "CONT-ELE-003",
    code: "ALT",
    price: 999.99,
    model: "Continental GT",
  },
  {
    name: "Timing Belt",
    sku: "CONT-ENG-004",
    code: "TB",
    price: 299.99,
    model: "Continental GT",
  },
  {
    name: "Water Pump",
    sku: "CONT-ENG-005",
    code: "WP",
    price: 199.99,
    model: "Continental GT",
  },

  // Cadillac Escalade
  {
    name: "Brake Pads",
    sku: "ESC-BRK-001",
    code: "BP",
    price: 399.99,
    model: "Escalade",
  },
  {
    name: "Oil Filter",
    sku: "ESC-ENG-001",
    code: "OF",
    price: 69.99,
    model: "Escalade",
  },
  {
    name: "Air Filter",
    sku: "ESC-ENG-002",
    code: "AF",
    price: 109.99,
    model: "Escalade",
  },
  {
    name: "Spark Plugs",
    sku: "ESC-ENG-003",
    code: "SP",
    price: 59.99,
    model: "Escalade",
  },
  {
    name: "Wiper Blades",
    sku: "ESC-EXT-001",
    code: "WB",
    price: 79.99,
    model: "Escalade",
  },
  {
    name: "Headlight Bulb",
    sku: "ESC-ELE-001",
    code: "HB",
    price: 69.99,
    model: "Escalade",
  },
  {
    name: "Battery",
    sku: "ESC-ELE-002",
    code: "BAT",
    price: 399.99,
    model: "Escalade",
  },
  {
    name: "Alternator",
    sku: "ESC-ELE-003",
    code: "ALT",
    price: 799.99,
    model: "Escalade",
  },
  {
    name: "Timing Belt",
    sku: "ESC-ENG-004",
    code: "TB",
    price: 299.99,
    model: "Escalade",
  },
  {
    name: "Water Pump",
    sku: "ESC-ENG-005",
    code: "WP",
    price: 199.99,
    model: "Escalade",
  },

  // Chevrolet Camaro
  {
    name: "Brake Pads",
    sku: "CAM-BRK-001",
    code: "BP",
    price: 79.99,
    model: "Camaro",
  },
  {
    name: "Oil Filter",
    sku: "CAM-ENG-001",
    code: "OF",
    price: 13.99,
    model: "Camaro",
  },
  {
    name: "Air Filter",
    sku: "CAM-ENG-002",
    code: "AF",
    price: 21.99,
    model: "Camaro",
  },
  {
    name: "Spark Plugs",
    sku: "CAM-ENG-003",
    code: "SP",
    price: 9.99,
    model: "Camaro",
  },
  {
    name: "Wiper Blades",
    sku: "CAM-EXT-001",
    code: "WB",
    price: 24.99,
    model: "Camaro",
  },
  {
    name: "Headlight Bulb",
    sku: "CAM-ELE-001",
    code: "HB",
    price: 17.99,
    model: "Camaro",
  },
  {
    name: "Battery",
    sku: "CAM-ELE-002",
    code: "BAT",
    price: 129.99,
    model: "Camaro",
  },
  {
    name: "Alternator",
    sku: "CAM-ELE-003",
    code: "ALT",
    price: 279.99,
    model: "Camaro",
  },
  {
    name: "Timing Belt",
    sku: "CAM-ENG-004",
    code: "TB",
    price: 44.99,
    model: "Camaro",
  },
  {
    name: "Water Pump",
    sku: "CAM-ENG-005",
    code: "WP",
    price: 79.99,
    model: "Camaro",
  },

  // Chrysler 300
  {
    name: "Brake Pads",
    sku: "300-BRK-001",
    code: "BP",
    price: 89.99,
    model: "300",
  },
  {
    name: "Oil Filter",
    sku: "300-ENG-001",
    code: "OF",
    price: 15.99,
    model: "300",
  },
  {
    name: "Air Filter",
    sku: "300-ENG-002",
    code: "AF",
    price: 24.99,
    model: "300",
  },
  {
    name: "Spark Plugs",
    sku: "300-ENG-003",
    code: "SP",
    price: 12.99,
    model: "300",
  },
  {
    name: "Wiper Blades",
    sku: "300-EXT-001",
    code: "WB",
    price: 29.99,
    model: "300",
  },
  {
    name: "Headlight Bulb",
    sku: "300-ELE-001",
    code: "HB",
    price: 19.99,
    model: "300",
  },
  {
    name: "Battery",
    sku: "300-ELE-002",
    code: "BAT",
    price: 149.99,
    model: "300",
  },
  {
    name: "Alternator",
    sku: "300-ELE-003",
    code: "ALT",
    price: 299.99,
    model: "300",
  },
  {
    name: "Timing Belt",
    sku: "300-ENG-004",
    code: "TB",
    price: 49.99,
    model: "300",
  },
  {
    name: "Water Pump",
    sku: "300-ENG-005",
    code: "WP",
    price: 89.99,
    model: "300",
  },

  // Dodge Challenger
  {
    name: "Brake Pads",
    sku: "CHL-BRK-001",
    code: "BP",
    price: 109.99,
    model: "Challenger",
  },
  {
    name: "Oil Filter",
    sku: "CHL-ENG-001",
    code: "OF",
    price: 19.99,
    model: "Challenger",
  },
  {
    name: "Air Filter",
    sku: "CHL-ENG-002",
    code: "AF",
    price: 29.99,
    model: "Challenger",
  },
  {
    name: "Spark Plugs",
    sku: "CHL-ENG-003",
    code: "SP",
    price: 15.99,
    model: "Challenger",
  },
  {
    name: "Wiper Blades",
    sku: "CHL-EXT-001",
    code: "WB",
    price: 39.99,
    model: "Challenger",
  },
  {
    name: "Headlight Bulb",
    sku: "CHL-ELE-001",
    code: "HB",
    price: 29.99,
    model: "Challenger",
  },
  {
    name: "Battery",
    sku: "CHL-ELE-002",
    code: "BAT",
    price: 199.99,
    model: "Challenger",
  },
  {
    name: "Alternator",
    sku: "CHL-ELE-003",
    code: "ALT",
    price: 399.99,
    model: "Challenger",
  },
  {
    name: "Timing Belt",
    sku: "CHL-ENG-004",
    code: "TB",
    price: 59.99,
    model: "Challenger",
  },
  {
    name: "Water Pump",
    sku: "CHL-ENG-005",
    code: "WP",
    price: 99.99,
    model: "Challenger",
  },

  // Dodge Durango
  {
    name: "Brake Pads",
    sku: "DUR-BRK-001",
    code: "BP",
    price: 129.99,
    model: "Durango",
  },
  {
    name: "Oil Filter",
    sku: "DUR-ENG-001",
    code: "OF",
    price: 22.99,
    model: "Durango",
  },
  {
    name: "Air Filter",
    sku: "DUR-ENG-002",
    code: "AF",
    price: 34.99,
    model: "Durango",
  },
  {
    name: "Spark Plugs",
    sku: "DUR-ENG-003",
    code: "SP",
    price: 19.99,
    model: "Durango",
  },
  {
    name: "Wiper Blades",
    sku: "DUR-EXT-001",
    code: "WB",
    price: 49.99,
    model: "Durango",
  },
  {
    name: "Headlight Bulb",
    sku: "DUR-ELE-001",
    code: "HB",
    price: 39.99,
    model: "Durango",
  },
  {
    name: "Battery",
    sku: "DUR-ELE-002",
    code: "BAT",
    price: 249.99,
    model: "Durango",
  },
  {
    name: "Alternator",
    sku: "DUR-ELE-003",
    code: "ALT",
    price: 499.99,
    model: "Durango",
  },
  {
    name: "Timing Belt",
    sku: "DUR-ENG-004",
    code: "TB",
    price: 79.99,
    model: "Durango",
  },
  {
    name: "Water Pump",
    sku: "DUR-ENG-005",
    code: "WP",
    price: 149.99,
    model: "Durango",
  },

  // Dodge Journey
  {
    name: "Brake Pads",
    sku: "JRN-BRK-001",
    code: "BP",
    price: 119.99,
    model: "Journey",
  },
  {
    name: "Oil Filter",
    sku: "JRN-ENG-001",
    code: "OF",
    price: 20.99,
    model: "Journey",
  },
  {
    name: "Air Filter",
    sku: "JRN-ENG-002",
    code: "AF",
    price: 32.99,
    model: "Journey",
  },
  {
    name: "Spark Plugs",
    sku: "JRN-ENG-003",
    code: "SP",
    price: 16.99,
    model: "Journey",
  },
  {
    name: "Wiper Blades",
    sku: "JRN-EXT-001",
    code: "WB",
    price: 44.99,
    model: "Journey",
  },
  {
    name: "Headlight Bulb",
    sku: "JRN-ELE-001",
    code: "HB",
    price: 34.99,
    model: "Journey",
  },
  {
    name: "Battery",
    sku: "JRN-ELE-002",
    code: "BAT",
    price: 229.99,
    model: "Journey",
  },
  {
    name: "Alternator",
    sku: "JRN-ELE-003",
    code: "ALT",
    price: 449.99,
    model: "Journey",
  },
  {
    name: "Timing Belt",
    sku: "JRN-ENG-004",
    code: "TB",
    price: 79.99,
    model: "Journey",
  },
  {
    name: "Water Pump",
    sku: "JRN-ENG-005",
    code: "WP",
    price: 149.99,
    model: "Journey",
  },

  // Dodge F-150
  {
    name: "Brake Pads",
    sku: "F150-BRK-001",
    code: "BP",
    price: 139.99,
    model: "F-150",
  },
  {
    name: "Oil Filter",
    sku: "F150-ENG-001",
    code: "OF",
    price: 24.99,
    model: "F-150",
  },
  {
    name: "Air Filter",
    sku: "F150-ENG-002",
    code: "AF",
    price: 39.99,
    model: "F-150",
  },
  {
    name: "Spark Plugs",
    sku: "F150-ENG-003",
    code: "SP",
    price: 22.99,
    model: "F-150",
  },
  {
    name: "Wiper Blades",
    sku: "F150-EXT-001",
    code: "WB",
    price: 59.99,
    model: "F-150",
  },
  {
    name: "Headlight Bulb",
    sku: "F150-ELE-001",
    code: "HB",
    price: 49.99,
    model: "F-150",
  },
  {
    name: "Battery",
    sku: "F150-ELE-002",
    code: "BAT",
    price: 299.99,
    model: "F-150",
  },
  {
    name: "Alternator",
    sku: "F150-ELE-003",
    code: "ALT",
    price: 599.99,
    model: "F-150",
  },
  {
    name: "Timing Belt",
    sku: "F150-ENG-004",
    code: "TB",
    price: 149.99,
    model: "F-150",
  },
  {
    name: "Water Pump",
    sku: "F150-ENG-005",
    code: "WP",
    price: 249.99,
    model: "F-150",
  },

  // Dodge Charger
  {
    name: "Brake Pads",
    sku: "CHG-BRK-001",
    code: "BP",
    price: 149.99,
    model: "Charger",
  },
  {
    name: "Oil Filter",
    sku: "CHG-ENG-001",
    code: "OF",
    price: 29.99,
    model: "Charger",
  },
  {
    name: "Air Filter",
    sku: "CHG-ENG-002",
    code: "AF",
    price: 49.99,
    model: "Charger",
  },
  {
    name: "Spark Plugs",
    sku: "CHG-ENG-003",
    code: "SP",
    price: 29.99,
    model: "Charger",
  },
  {
    name: "Wiper Blades",
    sku: "CHG-EXT-001",
    code: "WB",
    price: 69.99,
    model: "Charger",
  },
  {
    name: "Headlight Bulb",
    sku: "CHG-ELE-001",
    code: "HB",
    price: 59.99,
    model: "Charger",
  },
  {
    name: "Battery",
    sku: "CHG-ELE-002",
    code: "BAT",
    price: 399.99,
    model: "Charger",
  },
  {
    name: "Alternator",
    sku: "CHG-ELE-003",
    code: "ALT",
    price: 799.99,
    model: "Charger",
  },
  {
    name: "Timing Belt",
    sku: "CHG-ENG-004",
    code: "TB",
    price: 199.99,
    model: "Charger",
  },
  {
    name: "Water Pump",
    sku: "CHG-ENG-005",
    code: "WP",
    price: 299.99,
    model: "Charger",
  },

  // Tesla Model 3
  {
    name: "Brake Pads",
    sku: "M3-BRK-001",
    code: "BP",
    price: 159.99,
    model: "Model 3",
  },
  {
    name: "Oil Filter",
    sku: "M3-ENG-001",
    code: "OF",
    price: 29.99,
    model: "Model 3",
  },
  {
    name: "Air Filter",
    sku: "M3-ENG-002",
    code: "AF",
    price: 49.99,
    model: "Model 3",
  },
  {
    name: "Spark Plugs",
    sku: "M3-ENG-003",
    code: "SP",
    price: 29.99,
    model: "Model 3",
  },
  {
    name: "Wiper Blades",
    sku: "M3-EXT-001",
    code: "WB",
    price: 79.99,
    model: "Model 3",
  },
  {
    name: "Headlight Bulb",
    sku: "M3-ELE-001",
    code: "HB",
    price: 69.99,
    model: "Model 3",
  },
  {
    name: "Battery",
    sku: "M3-ELE-002",
    code: "BAT",
    price: 499.99,
    model: "Model 3",
  },
  {
    name: "Alternator",
    sku: "M3-ELE-003",
    code: "ALT",
    price: 999.99,
    model: "Model 3",
  },
  {
    name: "Timing Belt",
    sku: "M3-ENG-004",
    code: "TB",
    price: 299.99,
    model: "Model 3",
  },
  {
    name: "Water Pump",
    sku: "M3-ENG-005",
    code: "WP",
    price: 399.99,
    model: "Model 3",
  },
];

async function getModelId(modelName: string, db: Pool) {
  const result = await db.query("SELECT id FROM models WHERE name = $1", [
    modelName,
  ]);
  if (result.rows.length === 0) return null;
  return result.rows[0].id;
}

async function seedSpares() {
  const db = await connectPostgres();
  try {
    for (const spare of spares) {
      const modelId = await getModelId(spare.model, db);
      if (!modelId) {
        console.log(`Model ${spare.model} not found`);
        continue;
      }
      console.log(`Seeding ${spare.name} for ${spare.model}`);
      await db.query(
        "INSERT INTO spares (name, sku, code, price, model_id) VALUES ($1, $2, $3, $4, $5) ",
        [spare.name, spare.sku, spare.code, spare.price, modelId]
      );
    }
    console.log("Spares seeded successfully");
  } catch (error) {
    console.error("Error seeding roles:", error);
  } finally {
    await db.end();
  }
}

seedSpares();
